-- Found ament_cmake: 1.1.5 (/opt/ros/galactic/share/ament_cmake/cmake)
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.8.10", minimum required is "3") 
-- Using PYTHON_EXECUTABLE: /usr/bin/python3
-- Found rosidl_default_generators: 1.1.1 (/opt/ros/galactic/share/rosidl_default_generators/cmake)
-- Using all available rosidl_typesupport_c: rosidl_typesupport_fastrtps_c;rosidl_typesupport_introspection_c
-- Found rosidl_adapter: 2.2.1 (/opt/ros/galactic/share/rosidl_adapter/cmake)
-- Using all available rosidl_typesupport_cpp: rosidl_typesupport_fastrtps_cpp;rosidl_typesupport_introspection_cpp
-- Found PythonInterp: /usr/bin/python3 (found version "3.8.10") 
CMake Error at /opt/ros/galactic/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:60 (message):
  execute_process(/usr/bin/python3 -m rosidl_adapter --package-name
  customized_srv_msg --arguments-file
  /home/ghani/my_ws/build/customized_srv_msg/rosidl_adapter__arguments__customized_srv_msg.json
  --output-dir
  /home/ghani/my_ws/build/customized_srv_msg/rosidl_adapter/customized_srv_msg
  --output-file
  /home/ghani/my_ws/build/customized_srv_msg/rosidl_adapter/customized_srv_msg.idls)
  returned error code 1:

  Error processing 'int sequence' of 'customized_srv_msg/Fibonacci_Result':
  ''int' is an invalid message name.  It should have the pattern
  '^[A-Z][A-Za-z0-9]*$''

  Traceback (most recent call last):

    File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "/opt/ros/galactic/lib/python3.8/site-packages/rosidl_adapter/__main__.py", line 19, in <module>
      sys.exit(main())
    File "/opt/ros/galactic/lib/python3.8/site-packages/rosidl_adapter/main.py", line 53, in main
      abs_idl_file = convert_to_idl(
    File "/opt/ros/galactic/lib/python3.8/site-packages/rosidl_adapter/__init__.py", line 29, in convert_to_idl
      return convert_action_to_idl(
    File "/opt/ros/galactic/lib/python3.8/site-packages/rosidl_adapter/action/__init__.py", line 28, in convert_action_to_idl
      action = parse_action_string(package_name, input_file.stem, content)
    File "/opt/ros/galactic/lib/python3.8/site-packages/rosidl_adapter/parser.py", line 894, in parse_action_string
      result_message = parse_message_string(
    File "/opt/ros/galactic/lib/python3.8/site-packages/rosidl_adapter/parser.py", line 516, in parse_message_string
      Type(type_string, context_package_name=pkg_name),
    File "/opt/ros/galactic/lib/python3.8/site-packages/rosidl_adapter/parser.py", line 276, in __init__
      super(Type, self).__init__(
    File "/opt/ros/galactic/lib/python3.8/site-packages/rosidl_adapter/parser.py", line 204, in __init__
      raise InvalidResourceName(

  rosidl_adapter.parser.InvalidResourceName: 'int' is an invalid message
  name.  It should have the pattern '^[A-Z][A-Za-z0-9]*$'

Call Stack (most recent call first):
  /opt/ros/galactic/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:130 (rosidl_adapt_interfaces)
  CMakeLists.txt:12 (rosidl_generate_interfaces)


-- Configuring incomplete, errors occurred!
See also "/home/ghani/my_ws/build/customized_srv_msg/CMakeFiles/CMakeOutput.log".
make: *** [Makefile:1228: cmake_check_build_system] Error 1
